### ISSUE TITLE
AttributeError: 'str' object has no attribute 'x'

### ISSUE THREAD

**Issue by snowtyler** [KILLTUBE/corvid#12]
The following error appears when trying to convert a decompiled version of d2_prison_02.bsp using the standard Patch meshes brush conversion method with Corvid 0.0.4.

`Traceback (most recent call last):
  File "C:\Users\Mehmet\AppData\Local\Programs\Python\Python37\lib\threading.py", line 926, in _bootstrap_inner
  File "C:\Users\Mehmet\AppData\Local\Programs\Python\Python37\lib\threading.py", line 870, in run
  File "app.py", line 436, in convertButton_command
  File "C:\Users\Mehmet\Documents\GitHub\corvid\modules\MapExporter.py", line 605, in exportMap
  File "C:\Users\Mehmet\Documents\GitHub\corvid\modules\AssetExporter.py", line 757, in exportSkybox
AttributeError: 'str' object has no attribute 'x'`

Full log
[Corvid-log-27.07.2021_(11.17.45).txt](https://github.com/KILLTUBE/corvid/files/6886706/Corvid-log-27.07.2021_.11.17.45.txt)

**Comment by myuce** [comment]
I must have overlooked the part where it converts the skyboxes. I updated the release. Let me know if it works now so I can close the issue.

**Comment by snowtyler** [comment]
Just tried the new release, with the same exact settings it seems to be throwing a different error now.

`Traceback (most recent call last):
  File "C:\Users\Mehmet\AppData\Local\Programs\Python\Python37\lib\threading.py", line 926, in _bootstrap_inner
  File "C:\Users\Mehmet\AppData\Local\Programs\Python\Python37\lib\threading.py", line 870, in run
  File "app.py", line 436, in convertButton_command
  File "C:\Users\Mehmet\Documents\GitHub\corvid\modules\MapExporter.py", line 605, in exportMap
  File "C:\Users\Mehmet\Documents\GitHub\corvid\modules\AssetExporter.py", line 747, in exportSkybox
  File "C:\Users\Mehmet\Documents\GitHub\corvid\modules\Static.py", line 5, in Vector3FromStr
AttributeError: 'tuple' object has no attribute 'replace'`

[Corvid-log-27.07.2021_(16.17.05).txt](https://github.com/KILLTUBE/corvid/files/6888492/Corvid-log-27.07.2021_.16.17.05.txt)

**Comment by myuce** [comment]
Try it again. If it doesn't work, I'll remove the release for now and do further investigations.

**Comment by snowtyler** [comment]
Just downloaded the latest release and tried again, unfortunately it seems to get stuck at the same point ☹

`Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\Mehmet\AppData\Local\Programs\Python\Python37\lib\threading.py", line 926, in _bootstrap_inner
  File "C:\Users\Mehmet\AppData\Local\Programs\Python\Python37\lib\threading.py", line 870, in run
  File "app.py", line 436, in convertButton_command
  File "C:\Users\Mehmet\Documents\GitHub\corvid\modules\MapExporter.py", line 605, in exportMap
  File "C:\Users\Mehmet\Documents\GitHub\corvid\modules\AssetExporter.py", line 747, in exportSkybox
  File "C:\Users\Mehmet\Documents\GitHub\corvid\modules\Static.py", line 5, in Vector3FromStr
AttributeError: 'tuple' object has no attribute 'replace'`

[Corvid-log-28.07.2021_(11.31.25).txt](https://github.com/KILLTUBE/corvid/files/6894379/Corvid-log-28.07.2021_.11.31.25.txt)

**Comment by myuce** [comment]
I'm deleting the release and I'm going to do further tests before releasing it again to make sure everything works properly.

**Comment by myuce** [comment]
Was the map you tried to convert an original map from Half-Life or was it a custom one? If it's the former, could you tell me which one it is so I can test it to see if it will give me any errors? I want to make sure I won't have to update the release for a small bug.

**Comment by snowtyler** [comment]
It was d2_prison_02 from HL2, but I just tried it on a freshly bspsourced vmf with Corvid 0.0.3 and it appears to be working. A lot has changed with my PC configuration since I opened this so I'm unsure if I somehow caused the error myself, but since there weren't any issues converting I'll go ahead and close this.
