### ISSUE TITLE
Error thrown when converting 'bm_c1a0a_d' from Black Mesa

### ISSUE THREAD

**Issue by fusorf** [KILLTUBE/corvid#5]
Error at the end of step 10:

`Brush face 11474 has less than 3 vertices. Skipping...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\Mehmet\AppData\Local\Programs\Python\Python39\lib\threading.py", line 950, in _bootstrap_inner
  File "C:\Users\Mehmet\AppData\Local\Programs\Python\Python39\lib\threading.py", line 888, in run
  File "app.py", line 410, in convertButton_command
  File "C:\Users\Mehmet\Documents\GitHub\corvid\modules\MapExporter.py", line 616, in exportMap
  File "C:\Users\Mehmet\Documents\GitHub\corvid\modules\AssetExporter.py", line 719, in exportSkybox
TypeError: string indices must be integers
Exception in threading.excepthook:
Exception ignored in thread started by: <bound method Thread._bootstrap of <Thread(Thread-1, started 15036)>>
Traceback (most recent call last):
  File "C:\Users\Mehmet\AppData\Local\Programs\Python\Python39\lib\threading.py", line 908, in _bootstrap
  File "C:\Users\Mehmet\AppData\Local\Programs\Python\Python39\lib\threading.py", line 952, in _bootstrap_inner
  File "C:\Users\Mehmet\AppData\Local\Programs\Python\Python39\lib\threading.py", line 1220, in invoke_excepthook
AttributeError: 'TextRedirector' object has no attribute 'flush'
Exception ignored in sys.unraisablehook: <built-in function unraisablehook>
AttributeError: 'TextRedirector' object has no attribute 'flush'
`

Can't really understand this one, also paths point to dev's user folder.

**Comment by myuce** [comment]
It looks like an issue related to the conversion of the skybox texture. Will look into it soon.

> also paths point to dev's user folder.

That could be a side effect of using cx_Freeze to package the program. You can ignore that.

**Comment by myuce** [comment]
Looks like some skybox materials do not actually exist despite being referenced in the maps. This issue should be fixed after 519a6b46d97db73854357eedd2fc264cdec36849.
